language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=1
  - WP_VERSION=4.2 WP_MULTISITE=0
  - WP_VERSION=4.2 WP_MULTISITE=1
  - WP_VERSION=4.1 WP_MULTISITE=0
  - WP_VERSION=4.1 WP_MULTISITE=1

matrix:
  include:
    - php: 5.6
      env: WP_VERSION=latest
  allow_failures:
     - php: 5.6
  fast_finish: true

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION 

script: phpunit
